/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData line_width = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData redo = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser__1_ = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eraser = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData draw_icon = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData board = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_board = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData active_board = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
